[features]
seeds = true
skip-lint = false
[programs.localnet]
sol_cerberus = "SCERbrcgSPwgkrJ7j4TABr17dhYzdgiwPZUSSfFPt8x"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
#cluster = "devnet"
#cluster = "testnet"
#cluster = "mainnet"
wallet = "/Users/anderustarroz/.config/solana/SCFV.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
#test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/0_testing_macros.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./deps/mpl-token-metadata/programs/token-metadata/target/deploy/mpl_token_metadata.so"

[toolchain]
anchor_version = "0.29.0"  # `anchor-cli` version to use
solana_version = "1.16.20" # Solana version to use
