[package]
name = "sol-cerberus"
version = "0.1.0"
description = "A fine grained permission system for Solana"
edition = "2021"
authors = ["Ander", "Micael"]
homepage = "https://solcerberus.com/"
repository = "https://github.com/AnderUstarroz/sol-cerberus"
documentation = "https://solcerberus.com/docs"
readme = "README.md"
keywords = ["solana", "acl"]
categories = ["solana-access-control-list"]


[lib]
crate-type = ["cdylib", "lib"]
name = "sol_cerberus"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.26.0"
anchor-spl = { version = "0.26.0", features = ["metadata"] }
mpl-token-metadata = { version = "1.8.3", features = ["no-entrypoint"] }
